# ~/.config/alacritty/alacritty.toml

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.97
decorations = "None"

[font]
size = 12

[font.normal]
family = "InconsolataLGC Nerd Font"

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[colors.cursor]
text = "#1e1e1e"
cursor = "#d4d4d4"

[colors.selection]
text = "#ffffff"
background = "#264f78"

[colors.normal]
black   = "#000000"
red     = "#cd3131"
green   = "#0dbc79"
yellow  = "#e5e510"
blue    = "#2472c8"
magenta = "#bc3fbc"
cyan    = "#11a8cd"
white   = "#e5e5e5"

[colors.bright]
black   = "#666666"
red     = "#f14c4c"
green   = "#23d18b"
yellow  = "#f5f543"
blue    = "#3b8eea"
magenta = "#d670d6"
cyan    = "#29b8db"
white   = "#ffffff"
