# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = true

[python]
symbol = ""
pyenv_version_name = true
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true
