#!/usr/bin/sh

### Autostart
~/.config/polybar/launch.sh &
lxpolkit &
exec sxhkd &
nitrogen --random ~/Pictures/wallpapers/ --set-zoom-fill &
nitrogen --restore &
picom --experimental-backends --corner-radius 12 &
xsetroot -cursor_name left_ptr
# xmodmap -e "pointer = 1 2 3" &
xset r rate 400 40

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         3
bspc config window_gap           11
bspc config top_padding 44
# bspc config window_gap           20
# bspc config top_padding 40
bspc config ignore_ewmh_struts true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle			false
bspc config focus_follows_pointer	true

bspc rule -a discord desktop='^5'
bspc rule -a Steam desktop='^3'
bspc rule -a Pavucontrol desktop='^1'
bspc rule -a Org.gnome.Nautilus desktop='^1'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a NoiseTorch desktop='^8'
# bspc rule -a steam_app_1172470 desktop='^3'
# bspc rule -a steam_app_868270 desktop='^3'
bspc rule -a Viewnior state=floating
bspc rule -a Eog state=floating
# bspc rule -a discord desktop='^5' state=floating follow=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color		      "#6272a4"
bspc config active_border_color	        "#bd93f9"
bspc config focused_border_color	      "#bd93f9"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#ff5555"

